server:
    port: 9200

spring:
  application:
    name: study-zuul-user
  security:
    key:
      name: study
    expiretime: 3600000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://172.17.0.2:7001/eureka/


zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 160000
    connect-timeout-millis: 160000
#需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
      api-study:
        path: /api/**
        serviceId: study-user
