server:
  port: 8002

spring:
  application:
    name: study-service
  datasource:
        url: jdbc:mysql://192.168.196.100:3306/study?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

  redis:
    host: 192.168.196.100
    port: 6379
    database: 0

  aop:
    auto: true
    proxy-target-class: true


# mybatis-plus 配置
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hongtao.common.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    db-config:
      db-type: mysql

eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
