server:
  port: 9001
  
spring:
  application:
    name: study-user
  security:
    basic:
      enabled: false # 启用SpringSecurity的安全配置项
    key:
      name: study
    expiretime: 3600000
  servlet:
    multipart:
      max-file-size: 200Mb
      max-request-size: 200Mb

  #zipkin:
  #    base-url: http://localhost:9411
  redis:
    database: 0
    host: 192.168.196.100
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000

feign:
  hystrix:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
     defaultZone: http://172.17.0.2:7001/eureka/

