spring:
    profiles:
      active:
       - dev

---
server:
  port: 9002

spring:
  profiles: dev
  application:
    name: study-admin
  security:
    basic:
      enabled: false # 启用SpringSecurity的安全配置项
    key:
      name: study
    expiretime: 3600000

  #redis 用户session共享
  redis:
    database: 0
    host: 192.168.196.100
    port: 6379

feign:
  hystrix:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
     defaultZone: http://172.17.0.2:7001/eureka/

